# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ShFtZOLdL7EGJUNs4jX_k7ul3oCtJp3
"""

import matplotlib.pyplot as plt
import numpy as np
import random


def grafik(h, bl, title):
    plt.title(title)
    plt.xlabel("log(h)")
    plt.ylabel("log(E(h))")
    plt.grid()
    plt.plot(h, bl)
    plt.show()


x = 0.3
h = np.logspace(-32, 0, num=256, base=np.e, endpoint=False, dtype=np.double)
function = np.cos
log = np.log
pochodna = (function(x + h) - function(x)) / h
function_prim = -np.sin(x)
blad = np.abs(pochodna - function_prim)

grafik(log(h), log(blad), "grafik")

h = np.logspace(-64, 64, num=256, base=2, endpoint=False, dtype=np.double)

grafik(np.log(h), np.log(blad), "grafik")

x = 0.3
h = np.logspace(-32, 16, num=256, base=np.e, endpoint=False, dtype=np.double)
function = np.cos
log = np.log
pochodna = (function(x + h) - function(x - h)) / (2 * h)
function_prim = -np.sin(x)
blad = np.abs(pochodna - function_prim)

# grafik(np.log(h), np.log(blad), "2 funkcja")

h = np.logspace(-32, 16, num=256, base=np.e, endpoint=False, dtype=np.double)

# grafik(np.log(h), np.log(blad), "2 funkcja")
